upstream shop {
    server shop:8000;
}

upstream payments {
    server payments:8001;
}

server {
    listen 80;

    location /api/shop/ {
        proxy_pass http://shop/;
    }

    location /api/payments/ {
        proxy_pass http://payments/;
    }
}