# Generated by Django 6.0.2 on 2026-03-18 12:35

import user_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exampleuser',
            managers=[
                ('objects', user_account.models.ExampleUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='exampleuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
