events {}

http {
    default_type application/octet_stream;

    server_tokens off;
    limit_req_zone $binary_remote_addr zone=req_limit:10m rate=1r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
    upstream app {
        server app:8000 weight=1 max_fails=1 fail_timeout=60s;
#       server app_dupe:8001 weight=3 max_fails=3 fail_timeout=60s;
    }
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/cert.crt;
        #ssl_certificate_key /etc/nginx/certs/cert.ssl_certificate_key;
        ssl_certificate_key /etc/nginx/certs/cert.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        ssl_session_tickets off;

        limit_req zone=req_limit burst=20 nodelay;
        limit_conn conn_limit 20;

        location / {
            proxy_pass http://app;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-CSRFToken $cookie_csrf_token;
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
            add_header Access-Control-Allow-Headers "DNT, User-Agent, X-Requested-With, If-Modified-Since, Content-Type, Cache-Control, Authorization" always;
        }
        location /ws/ {
            proxy_pass http://app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
            add_header Access-Control-Allow-Headers "DNT, User-Agent, X-Requested-With, If-Modified-Since, Content-Type, Cache-Control, Authorization" always;

        }

        location /static/ {
            alias /code/static/;
            autoindex on;
            types {
                text/css css;
                application/javascript js;
                image/svg+xml svg;
            }
        }
    }

}